services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env 
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      nodemon src/index.js
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./server/app
          target: /app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./client/src/app
          target: /app/src/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
