# Generated by Django 5.2 on 2025-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
